spring:
  datasource:
    url: jdbc:oracle:thin:@dinkdb_high?TNS_ADMIN=./wallet
    username: team4
    password: Project12345
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 5
      pool-name: BaseHikariPool

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.OracleDialect


#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id:
#            client-secret:
#            scope:
#              - email


